/// The PDF statement (S-23, the Pro half of it — T-705).
///
/// A statement is a document you print, forward or file with a loan
/// application, so it is built the way the CSV is built: **Latin script, ISO
/// dates and plain rupees**. That is not a shortcut for the translations — the
/// screen that produces this file is fully translated, and the numbers are the
/// same numbers — it is a limit of the renderer behind this file: `pdf` is pure
/// Dart and has an Arabic/RTL pass but **no complex-script shaping engine**, so
/// Bengali and Devanagari would be laid out with their matras in the wrong
/// places. A statement that misprints `ক্যাটাগরি` is worse than one that prints
/// `Groceries`, so the labels and the category names are English here, exactly
/// as they are in the CSV. Merchant names are printed as the user typed them;
/// the Bengali fallback font is loaded only when some text actually needs it.
///
/// ₹ is safe: Manrope carries it, so no fallback is needed for the currency.
library;

import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// The Manrope face the app already ships — the same letterforms as the screen.
const String manropeAsset = 'assets/fonts/Manrope-VariableFont_wght.ttf';

/// Only loaded when a merchant name or a note contains Bengali.
const String notoBengaliAsset =
    'assets/fonts/NotoSansBengali-VariableFont_wght.ttf';

/// Only loaded for Devanagari text.
const String notoDevanagariAsset =
    'assets/fonts/NotoSansDevanagari-VariableFont_wght.ttf';

/// How a font is fetched. `rootBundle` in the app; a file read in tests, where
/// there is no asset bundle to ask.
typedef FontLoader = Future<ByteData> Function(String asset);

/// One line of the statement, already formatted for print.
class StatementRow {
  const StatementRow({
    required this.date,
    required this.particulars,
    required this.category,
    required this.amountPaise,
    required this.isIncome,
  });

  final String date;
  final String particulars;
  final String category;
  final int amountPaise;
  final bool isIncome;
}

/// Everything the document needs, in the order the page shows it.
class StatementData {
  const StatementData({
    required this.period,
    required this.rows,
    required this.incomePaise,
    required this.expensePaise,
    this.title = 'SpendStory statement',
    this.summaryLabels = const <String>[
      'Money in',
      'Money out',
      'Net',
      'Transactions',
    ],
    this.columnLabels = const <String>[
      'Date',
      'Particulars',
      'Category',
      'Amount',
    ],
    this.emptyLine = 'No transactions in this period.',
    this.footnote = '',
  });

  /// The document's own labels. English on purpose, like the CSV's column
  /// names: the renderer behind this file has no Indic shaping engine, so a
  /// Bengali label would print with its matras in the wrong order.
  final String title;
  final String period;
  final List<StatementRow> rows;
  final int incomePaise;
  final int expensePaise;

  /// [moneyIn, moneyOut, net, count] — already localized.
  final List<String> summaryLabels;

  /// [date, particulars, category, amount].
  final List<String> columnLabels;

  /// Printed in place of the table when the period is empty.
  final String emptyLine;

  /// The honesty line under the table ("generated on…, kept on your phone").
  final String footnote;

  int get netPaise => incomePaise - expensePaise;
}

/// `₹1,240.00`, Latin digits, always two decimals — the same shape as the CSV
/// column so a printed statement and a spreadsheet agree to the paisa.
String statementMoney(int paise) {
  final sign = paise < 0 ? '-' : '';
  final abs = paise.abs();
  final rupees = _grouped('${abs ~/ 100}');
  final paisePart = (abs % 100).toString().padLeft(2, '0');
  return '$sign₹$rupees.$paisePart';
}

/// `1234567` -> `1,234,567`. Integer arithmetic, like the CSV's amounts: a
/// statement that says `₹1239.999999` is worse than one that says nothing.
String _grouped(String digits) {
  final out = StringBuffer();
  for (var i = 0; i < digits.length; i++) {
    if (i > 0 && (digits.length - i) % 3 == 0) out.write(',');
    out.write(digits[i]);
  }
  return out.toString();
}

/// The line under the table: who made the file, when, and where the data came
/// from. The statement is Latin by design, so this is English too — and it is
/// the sentence that makes the file self-explanatory on a printer tray.
String statementFootnote(DateTime now) =>
    'Generated by SpendStory on ${statementDate(now.millisecondsSinceEpoch)} · '
    'made from data that never left the phone it was exported from.';

/// `07 Oct 2026`, Latin digits and month abbreviations, for the same reason.
String statementDate(int ms) {
  final d = DateTime.fromMillisecondsSinceEpoch(ms);
  return '${d.day.toString().padLeft(2, '0')} ${_monthAbbr[d.month - 1]} ${d.year}';
}

/// Three-letter months, spelled out here rather than asked of `intl`: the app's
/// own date helpers do the same, and a locale-data initialisation is not
/// something a document builder should be able to fail on.
const List<String> _monthAbbr = <String>[
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];

bool _hasRange(String text, int from, int to) {
  for (final rune in text.runes) {
    if (rune >= from && rune <= to) return true;
  }
  return false;
}

/// True when any visible text needs a script Manrope cannot draw.
bool needsFallbackFont(StatementData data) {
  final texts = <String>[
    data.title,
    data.period,
    data.emptyLine,
    data.footnote,
    ...data.summaryLabels,
    ...data.columnLabels,
    for (final row in data.rows) ...[row.date, row.particulars, row.category],
  ];
  return texts.any(
    (t) =>
        _hasRange(t, 0x0900, 0x097F) || // Devanagari
        _hasRange(t, 0x0980, 0x09FF), // Bengali
  );
}

/// Builds the statement. [loadFont] defaults to the app's asset bundle; tests
/// pass a reader that goes straight to the file.
Future<Uint8List> buildStatementPdf(
  StatementData data, {
  FontLoader? loadFont,
}) async {
  final load = loadFont ?? rootBundle.load;
  final base = pw.Font.ttf(await load(manropeAsset));
  final fallbacks = <pw.Font>[];
  if (needsFallbackFont(data)) {
    fallbacks
      ..add(pw.Font.ttf(await load(notoBengaliAsset)))
      ..add(pw.Font.ttf(await load(notoDevanagariAsset)));
  }

  final theme = pw.ThemeData.withFont(
    base: base,
    bold: base,
    italic: base,
    boldItalic: base,
    fontFallback: fallbacks,
  );

  final doc = pw.Document(title: data.title, theme: theme);

  // The totals block is the first thing a reader looks at, so it goes above the
  // table rather than under two hundred rows of it.
  final summary = <List<String>>[
    [data.summaryLabels[0], statementMoney(data.incomePaise)],
    [data.summaryLabels[1], statementMoney(data.expensePaise)],
    [data.summaryLabels[2], statementMoney(data.netPaise)],
    [data.summaryLabels[3], '${data.rows.length}'],
  ];

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.fromLTRB(32, 36, 32, 36),
      header: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            data.title,
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 2),
          pw.Text(
            data.period,
            style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          ),
          pw.Divider(color: PdfColors.grey400, height: 12),
        ],
      ),
      footer: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(height: 8),
          pw.Text(
            data.footnote,
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
          pw.SizedBox(height: 4),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              '${ctx.pageNumber} / ${ctx.pagesCount}',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
            ),
          ),
        ],
      ),
      build: (ctx) => [
        pw.SizedBox(height: 4),
        pw.TableHelper.fromTextArray(
          context: ctx,
          headers: const <String>['', ''],
          headerCount: 0,
          data: summary,
          columnWidths: {
            0: const pw.FlexColumnWidth(3),
            1: const pw.FlexColumnWidth(2),
          },
          cellStyle: const pw.TextStyle(fontSize: 10),
          cellPadding: const pw.EdgeInsets.symmetric(vertical: 3),
          border: null,
        ),
        pw.Divider(color: PdfColors.grey400, height: 14),
        if (data.rows.isEmpty)
          pw.Text(
            data.emptyLine,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          )
        else
          pw.TableHelper.fromTextArray(
            context: ctx,
            headers: data.columnLabels,
            data: [
              for (final row in data.rows)
                <String>[
                  row.date,
                  row.particulars,
                  row.category,
                  '${row.isIncome ? '+' : '-'}${statementMoney(row.amountPaise)}',
                ],
            ],
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(5),
              2: const pw.FlexColumnWidth(3),
              3: const pw.FlexColumnWidth(2.4),
            },
            headerStyle: pw.TextStyle(
              fontSize: 9,
              fontWeight: pw.FontWeight.bold,
            ),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
            cellStyle: const pw.TextStyle(fontSize: 9),
            cellPadding: const pw.EdgeInsets.symmetric(
              vertical: 3,
              horizontal: 4,
            ),
            cellAlignments: {3: pw.Alignment.centerRight},
          ),
      ],
    ),
  );

  return doc.save();
}
