#!/usr/bin/env python3
"""l10n_gen.py - turn the ARB files into the Dart table the UI reads.

`flutter gen-l10n` owns the framework half of localization: it generates
`AppLocalizations` from `lib/l10n/*.arb`, and `MaterialApp` hands that to
Flutter so the framework's own widgets (date pickers, text selection, tooltips)
speak the user's language.

The app's own copy needs one more thing that gen-l10n does not produce: a plain
`Map<locale, Map<key, String>>`, because 377 keys are read as
`SsStrings(locale)['key']` and sixteen of them are templates whose
`{placeholders}` are filled by `SsStrings.fill()` - gen-l10n turns those into
typed methods with positional arguments, which is the wrong shape for the
template engine and for the string tables the tests build directly.

(An extension of generated getters was tried and dropped: an extension only
resolves where its own library is imported, and half the screens reach
`SsStrings` through `stringsProvider`, never naming the type. The hand-written
getters in `lib/ui/strings.dart` are instance members and work everywhere.)

So the ARB files stay the single source of truth and are never hand-copied:

    lib/l10n/app_en.arb   (template - a key is born here)
    lib/l10n/app_hi.arb
    lib/l10n/app_bn.arb
        |
        +-- flutter gen-l10n ....... -> lib/l10n/app_localizations*.dart
        +-- python3 tool/l10n_gen.py -> lib/l10n/strings_table.g.dart

The script refuses to write anything unless the three files have exactly the
same keys, which is the same rule `test/l10n/l10n_test.dart` enforces on the
result - a missing translation is a red test, not an English leak in a Bengali
screen.

Run this script after editing any ARB. It formats its own output with
`dart format` when the SDK is on PATH; the guard against forgetting to run it is
`test/l10n/l10n_test.dart`, which compares the table back against the ARB files
(and is therefore blind to layout - only the copy matters).

Usage:
    python3 tool/l10n_gen.py           # regenerate lib/l10n/strings_table.g.dart
"""
from __future__ import annotations

import json
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ARB_DIR = ROOT / "lib" / "l10n"
OUT = ARB_DIR / "strings_table.g.dart"

LOCALES = ("en", "hi", "bn")
TEMPLATE = "en"


def read_arb(locale: str) -> dict[str, str]:
    path = ARB_DIR / f"app_{locale}.arb"
    data = json.loads(path.read_text(encoding="utf-8"))
    # "@key" entries are gen-l10n metadata; "@@locale" and friends are headers.
    return {k: v for k, v in data.items() if not k.startswith("@")}


def dart_string(value: str) -> str:
    """A double-quoted Dart literal. Double quotes keep every apostrophe in the
    copy readable, and the source is generated, so no lint cares."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def getter_name(key: str) -> str:
    """`budgetDaysLeftTemplate` -> `budgetDaysLeftTemplate` getter name.

    A key that is not a valid Dart identifier cannot become one; those stay
    reachable through `SsStrings['key']` only.
    """
    return key if re.fullmatch(r"[a-zA-Z_]\w*", key) else ""


def render(tables: dict[str, dict[str, str]], keys: list[str]) -> str:
    out: list[str] = []
    out.append(
        "// Generated by tool/l10n_gen.py from lib/l10n/app_en.arb,\n"
        "// app_hi.arb and app_bn.arb. Do not edit: edit the ARB files and run\n"
        "// the script (`python3 tool/l10n_gen.py`, then `dart format lib`).\n"
        "//\n"
        "// The ARB files are the single source of truth for user-facing copy.\n"
        "// test/l10n/l10n_test.dart compares this table against them key by key,\n"
        "// so an ARB edit that was never regenerated fails the build instead of\n"
        "// shipping a stale or missing translation.\n"
        "\n"
        "/// The per-locale string tables, straight from the ARB files.\n"
        "///\n"
        "/// Locale codes match [SsStrings.supportedLocales]. A template keeps its\n"
        "/// `{placeholders}` here; [SsStrings.fill] is what substitutes them.\n"
        "library;\n"
    )
    out.append("\n/// Every key, in template order.\n")
    out.append("const List<String> ssStringKeys = <String>[\n")
    for key in keys:
        out.append(f"  {dart_string(key)},\n")
    out.append("];\n")

    out.append(
        "\n/// The copy itself, as the screens read it.\n"
        "const Map<String, Map<String, String>> ssStringsTable =\n"
        "    <String, Map<String, String>>{"
        + ", ".join(f"{dart_string(loc)}: _{loc}" for loc in LOCALES)
        + "};\n"
    )

    for locale in LOCALES:
        out.append(
            f"\nconst Map<String, String> _{locale} = <String, String>{{\n"
        )
        for key in keys:
            name, value = dart_string(key), dart_string(tables[locale][key])
            line = f"  {name}: {value},"
            if len(line) <= 80:
                out.append(line + "\n")
            else:
                # What `dart format` does with an entry it cannot fit: the value
                # moves to its own line, indented past the key.
                out.append(f"  {name}:\n      {value},\n")
        out.append("};\n")

    return "".join(out)


def main(argv: list[str]) -> int:
    tables = {locale: read_arb(locale) for locale in LOCALES}
    keys = list(tables[TEMPLATE])

    for locale in LOCALES:
        missing = [k for k in keys if k not in tables[locale]]
        extra = [k for k in tables[locale] if k not in keys]
        if missing or extra:
            print(
                f"app_{locale}.arb does not match app_{TEMPLATE}.arb\n"
                f"  missing: {missing}\n  not in template: {extra}",
                file=sys.stderr,
            )
            return 1

    OUT.write_text(render(tables, keys), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} - {len(keys)} keys x {len(LOCALES)} locales")
    if shutil.which("dart"):
        subprocess.run(["dart", "format", str(OUT)], check=False)
    else:
        print("dart not on PATH - run `dart format lib/l10n/strings_table.g.dart`")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
